config/routes.rb
TripMap::Application.routes.draw do

  devise_for :users,
             :path => "",
             :path_names => { :sign_in => 'login', :sign_out => 'logout' },
             :skip => [:passwords, :registrations],
             :controllers => { :sessions => 'admin/sessions' }

  resources :accounts, only: [] do
    get 'new/:device_id' => 'accounts#new', as: 'new', on: :collection
    post ':device_id' => 'accounts#create', as: '', on: :collection
    get 'success' => 'accounts#success', on: :collection
  end

  namespace :admin do
    root :to => 'home#index'

    resources :maps, :except => :show do
      resources :images, except: :show
    end

    resources :provinces, :except => :show

    resources :places, :except => :show do
      resources :images, except: :show
    end

    resources :scenics, :except => :show do
      resources :images, except: :show
    end

    resources :serialnumbers, :except => :show do
      get  'search',    on: :collection
      get  'export',    on: :collection
      post 'ex_search', on: :collection

    end

    resources :settings, :only => [] do
      match "/" => "settings#index", on: :collection, via: [:get, :post]
    end

    resources :recommends do
      resources :images, except: :show
      resources :recommend_records,
                path: 'records',:as => "records" do
        resources :recommend_detaileds, path: 'detaileds', :as => "detaileds" do
          get    'video/new'  => 'recommend_detaileds#new_video'
          post   'videos'     => 'recommend_detaileds#create_video'
          put    'video/:id'  => 'recommend_detaileds#update_video',  :as => 'video'
          delete 'video/:id'  => 'recommend_detaileds#destroy_video'
          get    'videos/:id/edit' => 'recommend_detaileds#edit_video', :as => 'video_edit'

          get    'audio/new'  => 'recommend_detaileds#new_audio'
          post   'audios'     => 'recommend_detaileds#create_audio'
          put    'audio/:id'  => 'recommend_detaileds#update_audio',  :as => 'audio'
          delete 'audio/:id'  => 'recommend_detaileds#destroy_audio'
          get    'audios/:id/edit' => 'recommend_detaileds#edit_audio', :as => 'audio_edit'

          get    'image/new'  => 'recommend_detaileds#new_image'
          post   'images'     => 'recommend_detaileds#create_image'
          put    'image/:id'  => 'recommend_detaileds#update_image',  :as => 'image'
          delete 'image/:id'  => 'recommend_detaileds#destroy_image'
          get    'images/:id/edit' => 'recommend_detaileds#edit_image', :as => 'image_edit'

          get    'imagelist/new'  => 'recommend_detaileds#new_imagelist'
          post   'imagelists'     => 'recommend_detaileds#create_imagelist'
          put    'imagelist/:id'  => 'recommend_detaileds#update_imagelist',  :as => 'imagelist'
          delete 'imagelist/:id'  => 'recommend_detaileds#destroy_imagelist'
          get    'imagelists/:id/edit'   => 'recommend_detaileds#edit_imagelist', :as => 'imagelist_edit'

          get    'imagelist/:id/images/'  => 'recommend_detaileds#images', :as => 'imageslist'
          post   'imagelist/:image_id/images'   => 'recommend_detaileds#create_images'
          put    'imagelist/:image_id/image/:id' => 'recommend_detaileds#update_images', :as => 'photos'
          delete 'imagelist/:image_id/image/:id' => 'recommend_detaileds#destroy_images'
          get    'imagelist/:image_id/image/:id/edit' => 'recommend_detaileds#edit_images', :as => 'edit_images'
          get    'imagelist/:image_id/image/new' => 'recommend_detaileds#new_images', :as => 'new_images'

          get    'text/new'  => 'recommend_detaileds#new_text'
          post   'texts'     => 'recommend_detaileds#create_text'
          put    'text/:id'  => 'recommend_detaileds#update_text',  :as => 'text'
          delete 'text/:id'  => 'recommend_detaileds#destroy_text'
          get    'text/:id/edit' => 'recommend_detaileds#edit_text', :as => 'text_edit'

          get    'detailed_info/new'  => 'recommend_detaileds#new_detailed_info'
          post   'detailed_infos'     => 'recommend_detaileds#create_detailed_info'
          put    'detailed_info/:id'  => 'recommend_detaileds#update_detailed_info',  :as => 'detailed_info'
          delete 'detailed_info/:id'  => 'recommend_detaileds#destroy_detailed_info'
          get    'detailed_info/:id/edit' => 'recommend_detaileds#edit_detailed_info', :as => 'detailed_info_edit'

        end
      end
    end

    resources :specials, :except => :show do
      resources :minorities do
        resources :minority_slides, path: 'slides', :as => "slides", :except => :show
        resources :minority_feels, path: 'feels', :as => "feels", :except => :show
      end
    end
    
    resources :fights, :except => :show do
      resources :minorities do
        resources :minority_slides, path: 'slides', :as => "slides", :except => :show
        resources :minority_feels, path: 'feels', :as => "feels", :except => :show
      end
    end

    resources :minority_feels, :only => [] do
      resources :images, except: :show
    end

    resources :info_lists do
      resources :infos
    end

    resources :shares do
      get 'publish/:status', :action => :publish, :on => :member, :as => :publish
      match 'select', :on => :collection, :via => [:get, :post]
    end

    resources :cities, :except => :show

    resources :counties, :except => :show

    resources :merchants, :except => :show do
      resources :images, except: :show
    end

    resources :logs, :only => [:index, :show] do
      match 'select', :on => :collection, :via => [:get, :post]
    end

    resources :accounts, :except => :show do
      get 'search', :on => :collection
    end

    resources :api, :only => [] do
      get 'v1', :on => :collection
    end

    match 'declaration/show' => 'declarations#show', :as => 'declaration', :via => [:get, :post, :put]

    resources :feedbacks, only: [:index, :show]

    resources :versions

    resources :weathers, only: [:index]

    resources :surround_cities

    resources :lijiang_mailboxes, only: [ :index, :destroy ]

    resources :panel_videos

    resources :broadcasts do
      resources :children_broadcasts
    end

    resources :audio_list_categories do
      resources :audio_lists do
        resources :audio_list_items
      end
    end

    resources :first_knowns, :except => :show do
      resources :images, :except => :show
      resources :first_known_lists, :except => :show do
        resources :first_known_list_items
      end
    end

    resources :downloads, :only => [] do
      get '/d', :on => :collection
    end
  end

  namespace :api do
    namespace :v1 do

      resources :maps, :only => :index do
        resources :weathers, :only => :index
        get '/show', :on => :collection
        get '/validate', :on => :collection
        get 'shares/nearby' => 'shares#nearby', :on => :collection
        get 'shares/current' => 'shares#current', :on => :collection
        post 'shares/create' => 'shares#create', :on => :collection
        post 'logs' => 'logs#create', :on => :collection
        get 'version' => 'maps#version', :on => :member
      end

      resources :accounts, only: [] do
        post '/create' => 'accounts#create', on: :collection
        post '/login' => 'accounts#login', on: :collection
        post '/update' => 'accounts#update', on: :collection
        post '/validate' => 'accounts#validate', on: :collection
        get '/show' => 'accounts#show', on: :collection
      end

      resources :declarations, only: [] do
        get '/show' => 'declarations#show', on: :collection
      end

      resources :feedbacks, only: [] do
        post '/create' => 'feedbacks#create', on: :collection
      end

      resources :versions, only: [] do
        get '/check' => 'versions#check', :on => :collection
      end

      resources :downloads, only: [] do
        get '/count' => 'downloads#count', :on => :collection
      end

      resources :merchants, only: [:index, :show]
      resources :fights, only: [:index, :show]

      resources :devices, only: [:index] do
        post '/validate' => 'devices#validate', :on => :collection
        get '/unbind_device' => 'devices#unbind_device', :on => :collection
      end

      resources :lijiang_mailboxes, only: [:create]

      resources :offline_packages, only: [] do
        get '/pkg_versions' => 'offline_packages#pkg_versions', :on => :collection
        get '/get_all_pkg_infos' => 'offline_packages#get_all_pkg_infos', :on => :collection
        get '/get_offline_pkg_url' => 'offline_packages#get_offline_pkg_url', :on => :collection
      end

    end

    namespace :v1x do
      resources :maps, :only => :index do
      end
    end
  end

  root :to => 'home#index'
end

app/models/recommend.rb
class Recommend < ActiveRecord::Base

  attr_accessor :slug
  # White list
  attr_accessible :map, :map_id, :name, :is_free, :category_cd, :menu_type,
                  :slug, :recommend_slug_icon_attributes,
                  :recommend_cover_attributes, :recommend_video_attributes

  # Associations
  belongs_to :map, :counter_cache => true

  with_options :as => :videoable, :class_name => "Video", :dependent => :destroy do |assoc|
    assoc.has_one :recommend_video, :conditions => { :video_type => Video.recommend_video }
  end

  with_options :as => :imageable, :class_name => "Image", :dependent => :destroy do |assoc|
    assoc.has_one  :recommend_slug_icon, :conditions => { :image_type => Image.recommend_slug_icon }
    assoc.has_one  :recommend_cover,     :conditions => { :image_type => Image.recommend_cover }
    assoc.has_many :recommend_slides,    :conditions => { :image_type => Image.recommend_slides }
  end

  with_options :as => :keywordable, :class_name => "Keyword", :dependent => :destroy do |assoc|
    assoc.has_many :recommend_slugs,      :conditions => { :keyword_type => Keyword.recommend_slugs }
  end

  has_many :recommend_records, :dependent => :destroy

  # Enumeration, simple_enum plugin.
  as_enum :category, { one: 1, two: 2, three: 3 }

  # Validates
  with_options :presence => true do |column|
    column.validates :name, :length => { :within => 2..20 }, :uniqueness => true
    column.validates :map_id
    column.validates :category_cd
  end

  # Nested attributes validates
  accepts_nested_attributes_for :recommend_cover,     reject_if: ->(attr){ attr[:file].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :recommend_slug_icon, reject_if: ->(attr){ attr[:file].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :recommend_video,     reject_if: ->(attr){ (attr[:cover].blank? && attr[:id].blank?) }, :allow_destroy => true

  # Scopes
  scope :created_desc, order("`created_at` DESC")

end

app/controllers/admin/recommends_controller.rb
class Admin::RecommendsController < Admin::ApplicationController

  def index
    @recommends = Recommend.includes(:map).page(params[:page]).per(Setting.page_size).created_desc

    add_breadcrumb :index
  end

  def new
    @model = Recommend.new

    add_breadcrumb :new
  end

  def create
    add_breadcrumb :new
    @model = Recommend.new params[:recommend]
    if @model.save
      set_slug(params[:recommend][:slug], @model.recommend_slugs)
      redirect_to admin_recommends_path, notice: t('messages.recommends.success')
    else 
      render :new
    end
  end

  def edit
    add_breadcrumb :edit
    @model = Recommend.find params[:id]
    @model.slug = Keyword.get_slug(@model.recommend_slugs)
    @images = @model.recommend_slides.order_asc
  end

  def update
    add_breadcrumb :edit
    @model = Recommend.find params[:id]
    set_slug(params[:recommend][:slug], @model.recommend_slugs)
    if @model.update_attributes params[:recommend]
      redirect_to admin_recommends_path, notice: t('messages.recommends.success')
    else
      render :edit
    end
  end

  def destroy
    recommend = Recommend.find params[:id]
    if recommend.destroy
      redirect_to admin_recommends_path, notice: t('messages.recommends.success')
    else
      redirect_to admin_recommends_path, alert: t('messages.recommends.error')
    end
  end

end

app/views/admin/recommends/_base.html.erb
<div class="toolbar">
  <div class="btn-toolbar">
    <div class="btn-group">
      <%= link_to_if %w(index).include?(action_name), t('links.recommends.new') , new_admin_recommend_path, class: 'btn btn-success' %>
      <% if "edit update".include?(action_name) %>
        <%= link_to t('links.images.new'), 
                    new_admin_recommend_image_path(params[:id]), 
                    :class => 'btn btn-success' %>
      <% end -%>
      <%= link_to_if %w(new create edit update).include?(action_name), t('links.recommends.index'), admin_recommends_path, class: 'btn btn-success' %>
    </div>
  </div>
</div>

app/views/admin/recommends/_form.html.erb
<%= simple_form_for [:admin, @model], html: { class: 'form-horizontal' } do |r| %>
  <%= r.input :name %>
  <%= r.input :slug %>
  <%= r.input :is_free %>
  <%= r.input :menu_type %>
  <%= r.association :map, collection: Map.all, 
                          prompt: t("helpers.links.select", 
                          :model_name => Map.model_name.human) %>
  <%= r.input :category_cd do %>
      <%= r.select :category_cd, Recommend.categories_for_select(:value) %>
    <% end -%>
  <%= r.fields_for :recommend_cover, @model.recommend_cover ||= @model.build_recommend_cover do |c| %>
    <%= c.input :file, as: :file %>
    <% if @model.recommend_cover && @model.recommend_cover.file.present? %>
      <div class="control-group image">
        <div class="controls">
          <%= image_tag @model.recommend_cover.file %>
        </div>
      </div>
    <% end %>
  <% end %>

	<%= r.fields_for :recommend_slug_icon, @model.recommend_slug_icon ||= @model.build_recommend_slug_icon do |ricon| %>
  	<%= ricon.input :file, as: :file %>
    <% if @model.recommend_slug_icon && @model.recommend_slug_icon.file.present? %>
      <div class="control-group image">
        <div class="controls">
          <%= image_tag @model.recommend_slug_icon.file %>
        </div>
      </div>
    <% end %>
  <% end %>

  <%= r.fields_for :recommend_video, @model.recommend_video ||= @model.build_recommend_video do |v| %>
    <%= v.input :file, as: :file %>
    <%= v.input :cover, as: :file %>
    <%= v.input :duration %>
    <% if @model.recommend_video && @model.recommend_video.file.present? %>
      <div class="control-group">
        <div class="controls">
          <%= video_tag(@model.recommend_video.file, :controls => true, :autobuffer => true, :width => 400, :height => 240, :poster => @model.recommend_video.cover ) %>
        </div>
      </div>
    <%elsif @model.recommend_video && @model.recommend_video.cover.present? %>    
      <div class="control-group">
        <div class="controls">
          <%= image_tag(@model.recommend_video.cover) %>
        </div>
      </div>
    <% end %>
  <% end %>  
  <div class="form-actions">
    <%= r.button :submit, :class => 'btn-primary' %>
  </div>

<% end %>

app/views/admin/recommends/edit.html.erb
<%= render 'base' %>
<div class="box" %>
  <div class="box-title" %>
    <span class="icon"><i class="icon-edit"></i></span>
    <h5><%= t('links.recommends.edit') %></h5>
  </div>
  <div class="box-content no-padding" >
    <%= render 'form' %>
  </div>
</div>
<%= render "admin/images/index" %>

app/views/admin/recommends/index.html.erb
<%- model_class = Recommend -%>
<%= render 'base' %>
<div class="box">
  <div class="box-title">
    <span class="icon"><i class="icon-th"></i></span>
    <h5><%= t('links.recommends.index') %></h5>
  </div>
  <div class="box-content">
    <table class="table table-bordered table-striped with-check">
      <thead>
        <tr>
          <th>
            <input type="checkbox" id="title-table-checkbox" name="title-table-checkbox" />
          </th>
          <th><%= model_class.human_attribute_name(:name) %></th>
          <th><%= model_class.human_attribute_name(:recommend_slug) %></th>
          <th><%= model_class.human_attribute_name(:province) %></th>
          <th><%= model_class.human_attribute_name(:map) %></th>
          <th><%= model_class.human_attribute_name(:category_cd) %></th>
          <th><%= model_class.human_attribute_name(:recommend_records_count) %></th>
          <th><%= model_class.human_attribute_name(:is_free) %></th>
          <th><%= model_class.human_attribute_name(:menu_type) %></th>
          <th class="action"><%= t('links.commons.action') %></th>
        </thead>
        <tbody>
        <% if !@recommends.blank? %>
        <% @recommends.each do |r| %>
          <tr>
            <td><%= check_box_tag "province_ids[]", r.id, false, id: "province_#{r.id}" %></td>
            <td>
              <%= link_to r.name, admin_recommend_records_path(r) %>
            </td>
            <td><%= Keyword.get_slug(r.recommend_slugs) %></td>
            <td><%= r.map.province.name %></td>
            <td><%= r.map.name %></td>
            <td><%= t("enums.recommend.categories.#{model_class.categories.key(r.category_cd)}") %></td>
            <td><%=r.recommend_records_count %></td>
            <td><%=r.is_free %></td>
            <td><%=r.menu_type %></td>
            <td class="action">
              <%= link_to raw("<i class=\"icon-edit\"></i>"), edit_admin_recommend_path(r) %>
              <%= link_to raw("<i class=\"icon-trash\"></i>"), admin_recommend_path(r), method: :delete, data: { confirm: t('links.commons.confirm')} %>
            </td>
          </tr>
        <% end %>
        <% end %>
        </tbody>
      </table>
  </div>
</div>

<div class="table-footer clearfix">
  <div class="paginates-info"><%= page_entries_info @recommends %></div>
  <%= paginate @recommends, :theme => "admin" %>
</div>

app/views/admin/recommends/new.html.erb
<%= render "base" %>
<div class="box">
  <div class="box-title">
    <span class="icon"><i class="icon-pencil"></i></span>
    <h5><%= t('links.recommend_detaileds.new') %></h5>
  </div>
  <div class="box-content no-padding">
    <%= render "form" %>
  </div>
</div>