config/routes.rb
TripMap::Application.routes.draw do

  devise_for :users,
             :path => "",
             :path_names => { :sign_in => 'login', :sign_out => 'logout' },
             :skip => [:passwords, :registrations],
             :controllers => { :sessions => 'admin/sessions' }

  resources :accounts, only: [] do
    get 'new/:device_id' => 'accounts#new', as: 'new', on: :collection
    post ':device_id' => 'accounts#create', as: '', on: :collection
    get 'success' => 'accounts#success', on: :collection
  end

  namespace :admin do
    root :to => 'home#index'

    resources :maps, :except => :show do
      resources :images, except: :show
    end

    resources :provinces, :except => :show

    resources :places, :except => :show do
      resources :images, except: :show
    end

    resources :scenics, :except => :show do
      resources :images, except: :show
    end

    resources :serialnumbers, :except => :show do
      get  'search',    on: :collection
      get  'export',    on: :collection
      post 'ex_search', on: :collection

    end

    resources :settings, :only => [] do
      match "/" => "settings#index", on: :collection, via: [:get, :post]
    end

    resources :recommends do
      resources :images, except: :show
      resources :recommend_records,
                path: 'records',:as => "records" do
        resources :recommend_detaileds, path: 'detaileds', :as => "detaileds" do
          get    'video/new'  => 'recommend_detaileds#new_video'
          post   'videos'     => 'recommend_detaileds#create_video'
          put    'video/:id'  => 'recommend_detaileds#update_video',  :as => 'video'
          delete 'video/:id'  => 'recommend_detaileds#destroy_video'
          get    'videos/:id/edit' => 'recommend_detaileds#edit_video', :as => 'video_edit'

          get    'audio/new'  => 'recommend_detaileds#new_audio'
          post   'audios'     => 'recommend_detaileds#create_audio'
          put    'audio/:id'  => 'recommend_detaileds#update_audio',  :as => 'audio'
          delete 'audio/:id'  => 'recommend_detaileds#destroy_audio'
          get    'audios/:id/edit' => 'recommend_detaileds#edit_audio', :as => 'audio_edit'

          get    'image/new'  => 'recommend_detaileds#new_image'
          post   'images'     => 'recommend_detaileds#create_image'
          put    'image/:id'  => 'recommend_detaileds#update_image',  :as => 'image'
          delete 'image/:id'  => 'recommend_detaileds#destroy_image'
          get    'images/:id/edit' => 'recommend_detaileds#edit_image', :as => 'image_edit'

          get    'imagelist/new'  => 'recommend_detaileds#new_imagelist'
          post   'imagelists'     => 'recommend_detaileds#create_imagelist'
          put    'imagelist/:id'  => 'recommend_detaileds#update_imagelist',  :as => 'imagelist'
          delete 'imagelist/:id'  => 'recommend_detaileds#destroy_imagelist'
          get    'imagelists/:id/edit'   => 'recommend_detaileds#edit_imagelist', :as => 'imagelist_edit'

          get    'imagelist/:id/images/'  => 'recommend_detaileds#images', :as => 'imageslist'
          post   'imagelist/:image_id/images'   => 'recommend_detaileds#create_images'
          put    'imagelist/:image_id/image/:id' => 'recommend_detaileds#update_images', :as => 'photos'
          delete 'imagelist/:image_id/image/:id' => 'recommend_detaileds#destroy_images'
          get    'imagelist/:image_id/image/:id/edit' => 'recommend_detaileds#edit_images', :as => 'edit_images'
          get    'imagelist/:image_id/image/new' => 'recommend_detaileds#new_images', :as => 'new_images'

          get    'text/new'  => 'recommend_detaileds#new_text'
          post   'texts'     => 'recommend_detaileds#create_text'
          put    'text/:id'  => 'recommend_detaileds#update_text',  :as => 'text'
          delete 'text/:id'  => 'recommend_detaileds#destroy_text'
          get    'text/:id/edit' => 'recommend_detaileds#edit_text', :as => 'text_edit'

          get    'detailed_info/new'  => 'recommend_detaileds#new_detailed_info'
          post   'detailed_infos'     => 'recommend_detaileds#create_detailed_info'
          put    'detailed_info/:id'  => 'recommend_detaileds#update_detailed_info',  :as => 'detailed_info'
          delete 'detailed_info/:id'  => 'recommend_detaileds#destroy_detailed_info'
          get    'detailed_info/:id/edit' => 'recommend_detaileds#edit_detailed_info', :as => 'detailed_info_edit'

        end
      end
    end

    resources :specials, :except => :show do
      resources :minorities do
        resources :minority_slides, path: 'slides', :as => "slides", :except => :show
        resources :minority_feels, path: 'feels', :as => "feels", :except => :show
      end
    end
    
    resources :fights, :except => :show do
      resources :minorities do
        resources :minority_slides, path: 'slides', :as => "slides", :except => :show
        resources :minority_feels, path: 'feels', :as => "feels", :except => :show
      end
    end

    resources :minority_feels, :only => [] do
      resources :images, except: :show
    end

    resources :info_lists do
      resources :infos
    end

    resources :shares do
      get 'publish/:status', :action => :publish, :on => :member, :as => :publish
      match 'select', :on => :collection, :via => [:get, :post]
    end

    resources :cities, :except => :show

    resources :counties, :except => :show

    resources :merchants, :except => :show do
      resources :images, except: :show
    end

    resources :logs, :only => [:index, :show] do
      match 'select', :on => :collection, :via => [:get, :post]
    end

    resources :accounts, :except => :show do
      get 'search', :on => :collection
    end

    resources :api, :only => [] do
      get 'v1', :on => :collection
    end

    match 'declaration/show' => 'declarations#show', :as => 'declaration', :via => [:get, :post, :put]

    resources :feedbacks, only: [:index, :show]

    resources :versions

    resources :weathers, only: [:index]

    resources :surround_cities

    resources :lijiang_mailboxes, only: [ :index, :destroy ]

    resources :panel_videos

    resources :broadcasts do
      resources :children_broadcasts
    end

    resources :audio_list_categories do
      resources :audio_lists do
        resources :audio_list_items
      end
    end

    resources :first_knowns, :except => :show do
      resources :images, :except => :show
      resources :first_known_lists, :except => :show do
        resources :first_known_list_items
      end
    end

    resources :downloads, :only => [] do
      get '/d', :on => :collection
    end
  end

  namespace :api do
    namespace :v1 do

      resources :maps, :only => :index do
        resources :weathers, :only => :index
        get '/show', :on => :collection
        get '/validate', :on => :collection
        get 'shares/nearby' => 'shares#nearby', :on => :collection
        get 'shares/current' => 'shares#current', :on => :collection
        post 'shares/create' => 'shares#create', :on => :collection
        post 'logs' => 'logs#create', :on => :collection
        get 'version' => 'maps#version', :on => :member
      end

      resources :accounts, only: [] do
        post '/create' => 'accounts#create', on: :collection
        post '/login' => 'accounts#login', on: :collection
        post '/update' => 'accounts#update', on: :collection
        post '/validate' => 'accounts#validate', on: :collection
        get '/show' => 'accounts#show', on: :collection
      end

      resources :declarations, only: [] do
        get '/show' => 'declarations#show', on: :collection
      end

      resources :feedbacks, only: [] do
        post '/create' => 'feedbacks#create', on: :collection
      end

      resources :versions, only: [] do
        get '/check' => 'versions#check', :on => :collection
      end

      resources :downloads, only: [] do
        get '/count' => 'downloads#count', :on => :collection
      end

      resources :merchants, only: [:index, :show]
      resources :fights, only: [:index, :show]

      resources :devices, only: [:index] do
        post '/validate' => 'devices#validate', :on => :collection
        get '/unbind_device' => 'devices#unbind_device', :on => :collection
      end

      resources :lijiang_mailboxes, only: [:create]

      resources :offline_packages, only: [] do
        get '/pkg_versions' => 'offline_packages#pkg_versions', :on => :collection
        get '/get_all_pkg_infos' => 'offline_packages#get_all_pkg_infos', :on => :collection
        get '/get_offline_pkg_url' => 'offline_packages#get_offline_pkg_url', :on => :collection
      end

    end

    namespace :v1x do
      resources :maps, :only => :index do
      end
    end
  end

  root :to => 'home#index'
end

app/models/place.rb
class Place < ActiveRecord::Base

  attr_accessor :slug
  # White list
  attr_accessible :map, :map_id, :name, :subtitle, :is_free, :menu_type, :slug,
                  :place_icon_attributes, :place_slug_icon_attributes, :place_image_attributes,
                  :place_description_image_attributes, :place_video_attributes, :place_audio_attributes,
                  :place_description_attributes, :place_slides_attributes,
                  :place_slides_cover_attributes

  # Associations
  belongs_to :map, :counter_cache => true

  with_options :dependent => :destroy do |assoc|
    assoc.has_one :place_audio, :as => :audioable, :class_name => "Audio", :conditions => { :audio_type => Audio.place_audio }
    assoc.has_one :place_video, :as => :videoable, :class_name => "Video", :conditions => { :video_type => Video.place_video }
  end

  with_options :as => :imageable, :class_name => "Image", :dependent => :destroy do|assoc|
    assoc.has_one  :place_icon,               :conditions => { :image_type => Image.place_icon }
    assoc.has_one  :place_slug_icon,          :conditions => { :image_type => Image.place_slug_icon }
    assoc.has_one  :place_description_image,  :conditions => { :image_type => Image.place_description_image }
    assoc.has_one  :place_image,              :conditions => { :image_type => Image.place_image }
    assoc.has_one  :place_slides_cover,       :conditions => { :image_type => Image.place_slides_cover }
    assoc.has_many :place_slides,             :conditions => { :image_type => Image.place_slides }
  end

  with_options :as => :textable, :class_name => "Letter", :dependent => :destroy do|assoc|
    assoc.has_one  :place_description,        :conditions => { :text_type => Letter.place_description }
  end

  with_options :as => :keywordable, :class_name => 'Keyword', :dependent => :destroy do|assoc|
    assoc.has_many :place_slugs,                :conditions => { :keyword_type => Keyword.place_slugs }
  end

  # Validates
  with_options :presence => true do |column|
    column.validates :name, :length => { :within => 2..20 }
    column.validates :map_id
    column.validates :subtitle, :length => { :within => 2..30 }
  end

  # Nested attributes validates
  accepts_nested_attributes_for :place_icon,              reject_if: ->(attr){ attr[:file].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :place_slug_icon,         reject_if: ->(attr){ attr[:file].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :place_description_image, reject_if: ->(attr){ attr[:file].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :place_image,             reject_if: ->(attr){ attr[:file].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :place_slides_cover,      reject_if: ->(attr){ attr[:file].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :place_audio,             reject_if: ->(attr){ attr[:file].blank? && attr[:id].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :place_video,             reject_if: ->(attr){ attr[:file].blank? && attr[:id].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :place_description,       :allow_destroy => true
  accepts_nested_attributes_for :place_slides,            :allow_destroy => true

  # Scopes
  scope :created_desc, order("`created_at` DESC")

end

app/controllers/admin/places_controller.rb
class Admin::PlacesController < Admin::ApplicationController

  def index
    @places = Place.includes(:map).page(params[:page]).per(Setting.page_size).created_desc

    add_breadcrumb :index
  end

  def new
    @model = Place.new

    add_breadcrumb :new
  end

  def create
    add_breadcrumb :new
    @model = Place.new params[:place]
    if @model.save
      set_slug(params[:place][:slug], @model.place_slugs)
      redirect_to admin_places_path, notice: t('messages.places.success')
    else
      render :new
    end
  end

  def edit
    @model = Place.find params[:id]
    @model.slug = Keyword.get_slug(@model.place_slugs)
    @images = @model.place_slides.order_asc
    add_breadcrumb :edit
  end

  def update
    add_breadcrumb :edit
    @model = Place.find params[:id]
    set_slug(params[:place][:slug], @model.place_slugs)
    if @model.update_attributes params[:place]
      redirect_to admin_places_path, notice: t('messages.places.success')
    else
      render :edit
    end
  end

  def destroy
    @place = Place.find params[:id]
    if @place.destroy
      redirect_to admin_places_path, notice: t('messages.places.success')
    else
      redirect_to admin_places_path, alert: t('messages.places.error')
    end
  end

end

app/views/admin/places/_base.html.erb
<div class="toolbar">
  <div class="btn-toolbar">
    <div class="btn-group">
      <%= link_to_if %w(index).include?(action_name), t('links.places.new'), new_admin_place_path, class: 'btn btn-success' %>
      <% if "edit update".include?(action_name) %>
        <%= link_to t('links.images.new'), 
                    new_admin_place_image_path(params[:id]), 
                    :class => 'btn btn-success' %>
      <% end -%>
      <%= link_to_if %w(new create edit update).include?(action_name), t('links.places.index'), admin_places_path, class: 'btn btn-success' %>
    </div>
  </div>
</div>

app/views/admin/places/_form.html.erb
<%= simple_form_for [:admin,@model], html: { class: 'form-horizontal' } do |p| %>
  <%= p.input :name %>
  <%= p.input :slug %>
  <%= p.input :is_free %>
  <%= p.input :menu_type %>
  <%= p.input :subtitle %>
  <%= p.association :map, collection: Map.all, prompt: t("helpers.links.select", :model_name => Map.model_name.human) %>

  <%= p.fields_for :place_icon, @model.place_icon ||= @model.build_place_icon do |picon|  %>  
    <%= picon.input :file, :as => :file %>
    <% if @model.place_icon && @model.place_icon.file.present? %>
        <div class="control-group image">
          <div class="controls">
            <%= image_tag @model.place_icon.file %>
          </div>
        </div>
    <% end %>
  <% end %>

  <%= p.fields_for :place_slug_icon, @model.place_slug_icon ||= @model.build_place_slug_icon do |picon| %>
  <%= picon.input :file, as: :file %>
    <% if @model.place_slug_icon && @model.place_slug_icon.file.present? %>
      <div class="control-group image">
        <div class="controls">
          <%= image_tag @model.place_slug_icon.file %>
        </div>
      </div>
    <% end %>
  <% end %>

  <%= p.fields_for :place_image, @model.place_image ||= @model.build_place_image do |pimg|  %>  
    <%= pimg.input :file, :as => :file %>
    <% if @model.place_image && @model.place_image.file.present? %>
      <div class="control-group image">
        <div class="controls">
          <%= image_tag @model.place_image.file %>
        </div>
      </div>
    <% end %>
  <% end %>

  <%= p.fields_for :place_audio, @model.place_audio ||= @model.build_place_audio do |pa|  %>  
    <%= pa.input :file, :as => :file %>
    <%= pa.input :duration %>
    <%= pa.input :order %>
     <% if @model.place_audio && @model.place_audio.file.present? %>
      <div class="control-group">
        <div class="controls">
          <%= audio_tag(@model.place_audio.file, :autoplay => false, :controls => true) %>
        </div>
      </div>
    <% end %>
  <% end %>

  <%= p.fields_for :place_video, @model.place_video ||= @model.build_place_video do |pv|  %>  
    <%= pv.input :file,  :as => :file %>
    <%= pv.input :cover, :as => :file %>
    <%= pv.input :duration %>
    <%= pv.input :order %>

    <% if @model.place_video && @model.place_video.file.present? %>
      <div class="control-group">
        <div class="controls">
          <%= video_tag(@model.place_video.file, :controls => true, :autobuffer => true, :width => 400, :height => 240, :poster => @model.place_video.cover ) %>
        </div>
      </div>
    <% end %>
  <% end %>

  <%= p.fields_for :place_slides_cover, @model.place_slides_cover ||= @model.build_place_slides_cover do |sicon| %>
    <%= sicon.input :file, as: :file %>

    <% if @model.place_slides_cover && @model.place_slides_cover.file.present? %>
      <div class="control-group image">
        <div class="controls">
          <%= image_tag @model.place_slides_cover.file %>
        </div>
      </div>
    <% end %>
  <% end %>

  <%= p.fields_for :place_description, 
                   @model.place_description ||= @model.build_place_description do |pd|  %>  
    <%= pd.input :body, :as => :text, input_html: { :class => "span-full"} %>
  <% end %>

  <div class="form-actions">
    <%= p.button :submit, :class => 'btn-primary' %>
  </div>
<% end %>

app/views/admin/places/edit.html.erb
<%= render 'base' %>
<div class="box">
  <div class="box-title">
    <span class="icon"><i class="icon-edit"></i></span>
    <h5><%= t('links.places.edit') %></h5>
  </div>
  <div class="box-content no-padding">
    <%= render 'form' %>
  </div>
</div>
<%= render "admin/images/index" %>

app/views/admin/places/index.html.erb
<%- model_class = Place -%>

<%= render 'base' %>

<div class="box">
  <div class="box-title">
    <span class="icon"><i class="icon-th"></i></span>
    <h5><%= t('links.places.index') %></h5>
  </div>
  <div class="box-content">
    <table class="table table-bordered table-striped with-check">
      <thead>
        <tr>
          <th><input type="checkbox" id="title-table-checkbox" name="title-table-checkbox" /></th>
          <th><%= model_class.human_attribute_name(:name) %></th>
          <th><%= model_class.human_attribute_name(:place_slug) %></th>
          <th><%= model_class.human_attribute_name(:province) %></th>
          <th><%= model_class.human_attribute_name(:map) %></th>
          <th><%= model_class.human_attribute_name(:is_free) %></th>
          <th><%= model_class.human_attribute_name(:menu_type) %></th>
          <th><%= model_class.human_attribute_name(:place_slides_cover) %></th>
          <th class="action"><%= t('links.commons.action') %></th>
        </tr>
      </thead>
      <tbody>
      <% @places.each do |p| %>
        <tr>
          <td><%= check_box_tag "place_ids[]", p.id, false, id: "place_#{p.id}" %></td>
          <td><%= p.name %></td>
          <td><%= Keyword.get_slug(p.place_slugs) %></td>
          <td><%= p.map.province.name %></td>
          <td><%= p.map.name %></td>
          <td><%= p.is_free %></td>
          <td><%= p.menu_type %></td>
          <td><%= image_tag p.place_slides_cover.file, :size => "35x35" unless p.place_slides_cover.blank? %></td>

          <td class="action">
            <%= link_to raw("<i class=\"icon-edit\"></i>"), edit_admin_place_path(p), title: t('links.places.edit') %>
            <%= link_to raw("<i class=\"icon-trash\"></i>"), admin_place_path(p), method: :delete, data: {confirm: t('links.commons.confirm')} %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>
<div class="table-footer clearfix">
  <div class="paginates-info"><%= page_entries_info @places %></div>
  <%= paginate @places, :theme => "admin" %>
</div>

app/views/admin/places/new.html.erb
<% render "base" %>
<div class="box" %>
	<div class="box-title">
	<span class="icon"><i class="icon-pencil"></i></span>
	<h5><%= t('links.places.new') %></h5>
	</div>
	<div class="box-content no-padding">
		<%= render "form" %>
	</div>
</div>