config/routes.rb
TripMap::Application.routes.draw do

  devise_for :users,
             :path => "",
             :path_names => { :sign_in => 'login', :sign_out => 'logout' },
             :skip => [:passwords, :registrations],
             :controllers => { :sessions => 'admin/sessions' }

  resources :accounts, only: [] do
    get 'new/:device_id' => 'accounts#new', as: 'new', on: :collection
    post ':device_id' => 'accounts#create', as: '', on: :collection
    get 'success' => 'accounts#success', on: :collection
  end

  namespace :admin do
    root :to => 'home#index'

    resources :maps, :except => :show do
      resources :images, except: :show
    end

    resources :provinces, :except => :show

    resources :places, :except => :show do
      resources :images, except: :show
    end

    resources :scenics, :except => :show do
      resources :images, except: :show
    end

    resources :serialnumbers, :except => :show do
      get  'search',    on: :collection
      get  'export',    on: :collection
      post 'ex_search', on: :collection

    end

    resources :settings, :only => [] do
      match "/" => "settings#index", on: :collection, via: [:get, :post]
    end

    resources :recommends do
      resources :images, except: :show
      resources :recommend_records,
                path: 'records',:as => "records" do
        resources :recommend_detaileds, path: 'detaileds', :as => "detaileds" do
          get    'video/new'  => 'recommend_detaileds#new_video'
          post   'videos'     => 'recommend_detaileds#create_video'
          put    'video/:id'  => 'recommend_detaileds#update_video',  :as => 'video'
          delete 'video/:id'  => 'recommend_detaileds#destroy_video'
          get    'videos/:id/edit' => 'recommend_detaileds#edit_video', :as => 'video_edit'

          get    'audio/new'  => 'recommend_detaileds#new_audio'
          post   'audios'     => 'recommend_detaileds#create_audio'
          put    'audio/:id'  => 'recommend_detaileds#update_audio',  :as => 'audio'
          delete 'audio/:id'  => 'recommend_detaileds#destroy_audio'
          get    'audios/:id/edit' => 'recommend_detaileds#edit_audio', :as => 'audio_edit'

          get    'image/new'  => 'recommend_detaileds#new_image'
          post   'images'     => 'recommend_detaileds#create_image'
          put    'image/:id'  => 'recommend_detaileds#update_image',  :as => 'image'
          delete 'image/:id'  => 'recommend_detaileds#destroy_image'
          get    'images/:id/edit' => 'recommend_detaileds#edit_image', :as => 'image_edit'

          get    'imagelist/new'  => 'recommend_detaileds#new_imagelist'
          post   'imagelists'     => 'recommend_detaileds#create_imagelist'
          put    'imagelist/:id'  => 'recommend_detaileds#update_imagelist',  :as => 'imagelist'
          delete 'imagelist/:id'  => 'recommend_detaileds#destroy_imagelist'
          get    'imagelists/:id/edit'   => 'recommend_detaileds#edit_imagelist', :as => 'imagelist_edit'

          get    'imagelist/:id/images/'  => 'recommend_detaileds#images', :as => 'imageslist'
          post   'imagelist/:image_id/images'   => 'recommend_detaileds#create_images'
          put    'imagelist/:image_id/image/:id' => 'recommend_detaileds#update_images', :as => 'photos'
          delete 'imagelist/:image_id/image/:id' => 'recommend_detaileds#destroy_images'
          get    'imagelist/:image_id/image/:id/edit' => 'recommend_detaileds#edit_images', :as => 'edit_images'
          get    'imagelist/:image_id/image/new' => 'recommend_detaileds#new_images', :as => 'new_images'

          get    'text/new'  => 'recommend_detaileds#new_text'
          post   'texts'     => 'recommend_detaileds#create_text'
          put    'text/:id'  => 'recommend_detaileds#update_text',  :as => 'text'
          delete 'text/:id'  => 'recommend_detaileds#destroy_text'
          get    'text/:id/edit' => 'recommend_detaileds#edit_text', :as => 'text_edit'

          get    'detailed_info/new'  => 'recommend_detaileds#new_detailed_info'
          post   'detailed_infos'     => 'recommend_detaileds#create_detailed_info'
          put    'detailed_info/:id'  => 'recommend_detaileds#update_detailed_info',  :as => 'detailed_info'
          delete 'detailed_info/:id'  => 'recommend_detaileds#destroy_detailed_info'
          get    'detailed_info/:id/edit' => 'recommend_detaileds#edit_detailed_info', :as => 'detailed_info_edit'

        end
      end
    end

    resources :specials, :except => :show do
      resources :minorities do
        resources :minority_slides, path: 'slides', :as => "slides", :except => :show
        resources :minority_feels, path: 'feels', :as => "feels", :except => :show
      end
    end
    
    resources :fights, :except => :show do
      resources :minorities do
        resources :minority_slides, path: 'slides', :as => "slides", :except => :show
        resources :minority_feels, path: 'feels', :as => "feels", :except => :show
      end
    end

    resources :minority_feels, :only => [] do
      resources :images, except: :show
    end

    resources :info_lists do
      resources :infos
    end

    resources :shares do
      get 'publish/:status', :action => :publish, :on => :member, :as => :publish
      match 'select', :on => :collection, :via => [:get, :post]
    end

    resources :cities, :except => :show

    resources :counties, :except => :show

    resources :merchants, :except => :show do
      resources :images, except: :show
    end

    resources :logs, :only => [:index, :show] do
      match 'select', :on => :collection, :via => [:get, :post]
    end

    resources :accounts, :except => :show do
      get 'search', :on => :collection
    end

    resources :api, :only => [] do
      get 'v1', :on => :collection
    end

    match 'declaration/show' => 'declarations#show', :as => 'declaration', :via => [:get, :post, :put]

    resources :feedbacks, only: [:index, :show]

    resources :versions

    resources :weathers, only: [:index]

    resources :surround_cities

    resources :lijiang_mailboxes, only: [ :index, :destroy ]

    resources :panel_videos

    resources :broadcasts do
      resources :children_broadcasts
    end

    resources :audio_list_categories do
      resources :audio_lists do
        resources :audio_list_items
      end
    end

    resources :first_knowns, :except => :show do
      resources :images, :except => :show
      resources :first_known_lists, :except => :show do
        resources :first_known_list_items
      end
    end

    resources :downloads, :only => [] do
      get '/d', :on => :collection
    end
  end

  namespace :api do
    namespace :v1 do

      resources :maps, :only => :index do
        resources :weathers, :only => :index
        get '/show', :on => :collection
        get '/validate', :on => :collection
        get 'shares/nearby' => 'shares#nearby', :on => :collection
        get 'shares/current' => 'shares#current', :on => :collection
        post 'shares/create' => 'shares#create', :on => :collection
        post 'logs' => 'logs#create', :on => :collection
        get 'version' => 'maps#version', :on => :member
      end

      resources :accounts, only: [] do
        post '/create' => 'accounts#create', on: :collection
        post '/login' => 'accounts#login', on: :collection
        post '/update' => 'accounts#update', on: :collection
        post '/validate' => 'accounts#validate', on: :collection
        get '/show' => 'accounts#show', on: :collection
      end

      resources :declarations, only: [] do
        get '/show' => 'declarations#show', on: :collection
      end

      resources :feedbacks, only: [] do
        post '/create' => 'feedbacks#create', on: :collection
      end

      resources :versions, only: [] do
        get '/check' => 'versions#check', :on => :collection
      end

      resources :downloads, only: [] do
        get '/count' => 'downloads#count', :on => :collection
      end

      resources :merchants, only: [:index, :show]
      resources :fights, only: [:index, :show]

      resources :devices, only: [:index] do
        post '/validate' => 'devices#validate', :on => :collection
        get '/unbind_device' => 'devices#unbind_device', :on => :collection
      end

      resources :lijiang_mailboxes, only: [:create]

      resources :offline_packages, only: [] do
        get '/pkg_versions' => 'offline_packages#pkg_versions', :on => :collection
        get '/get_all_pkg_infos' => 'offline_packages#get_all_pkg_infos', :on => :collection
        get '/get_offline_pkg_url' => 'offline_packages#get_offline_pkg_url', :on => :collection
      end

    end

    namespace :v1x do
      resources :maps, :only => :index do
      end
    end
  end

  root :to => 'home#index'
end

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : Setting.app_name %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "admin/application", :media => "all" %>
  </head>

  <body id="<%= "#{controller_name}-#{action_name}" %>">
    <% if %w(sessions).include?(controller_name) %>
       <%= render "layouts/admin_login" %>
       <div class="navbar navbar-fixed-top">
      </div>
    <% else %>
      <div class="navbar navbar-fixed-top">
        <div class="navbar-inner">
          <div class="container">
            <a class="brand" href="#"><%= Setting.app_name %></a>
            <div class="container nav-collapse">
              <ul class="nav">
                <li<%= raw ' class="active"' if %w(home).include?(controller_name) %>>
                  <%= link_to t("navs.home.index"), admin_root_path %>
                </li>
                <li<%= raw ' class="active"' if %w(provinces) .include?(controller_name) %>>
                  <%= link_to t("navs.provinces.index"), admin_provinces_path %>
                </li>
                <li class="dropdown <%= raw 'active' if %w(maps scenics places recommends info_lists).include?(controller_name) %>">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      <%= t("navs.maps.index")%><b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                      <li><%= link_to t("navs.maps.index"), admin_maps_path %></li>
                      <li class="divider"></li>
                      <li><%= link_to t("navs.scenics.index"), admin_scenics_path %></li>
                      <li><%= link_to t("navs.places.index"), admin_places_path %></li>
                      <li><%= link_to t("navs.recommends.index"), admin_recommends_path %></li>
                      <li><%= link_to t("navs.info_lists.index"), admin_info_lists_path %></li>
                      <li><%= link_to t("navs.panel_videos.index"), admin_panel_videos_path %></li>
                      <li><%= link_to t("navs.broadcasts.index"), admin_broadcasts_path %></li>
                      <li><%= link_to t("navs.specials.index"), admin_specials_path %></li>
                      <li><%= link_to t("navs.audio_list_categories.index"), admin_audio_list_categories_path %></li>
                      <li><%= link_to t("navs.first_knowns.index"), admin_first_knowns_path %></li>
                    </ul>
                  </li>
                <li<%= raw ' class="active"' if %w(shares).include?(controller_name) %>>
                  <%= link_to t("navs.shares.index"), admin_shares_path %>
                </li>
                <li class="dropdown <%= raw 'active' if %w(cities counties merchants).include?(controller_name) %>">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <%= t("navs.merchants.index")%><b class="caret"></b>
                  </a>
                  <ul class="dropdown-menu">
                    <li> <%= link_to t("navs.merchants.index"), admin_merchants_path %></li>
                    <li> <%= link_to t("navs.fights.index"), admin_fights_path %></li>
                    <li class="divider"></li>
                    <li><%= link_to t("navs.cities.index"), admin_cities_path %></li>
                    <li><%= link_to t("navs.counties.index"), admin_counties_path %></li>
                  </ul>
                </li>
                <li class="dropdown <%= raw 'active' if %w(accounts feedbacks).include?(controller_name) %>">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <%= t("navs.accounts.index")%><b class="caret"></b>
                  </a>
                  <ul class="dropdown-menu">
                    <li> <%= link_to t("navs.accounts.index"), admin_accounts_path %></li>
                    <li class="divider"></li>
                    <li><%= link_to t("navs.feedbacks.index"), admin_feedbacks_path %></li>
                  </ul>
                </li>
                <li<%= raw ' class="active"' if %w(logs).include?(controller_name) %>>
                  <%= link_to t("navs.logs.index"), admin_logs_path %>
                </li>
                <li<%= raw ' class="active"' if %w(api).include?(controller_name) %>>
                  <%= link_to t("navs.apis.index"), v1_admin_api_index_path %>
                </li>
                <li<%= raw ' class="active"' if %w(serialnumbers).include?(controller_name) %>>
                  <%= link_to t("navs.serialnumber.index"), admin_serialnumbers_path %>
                </li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%=t("navs.settings.index")%><b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to t("navs.declarations.show"), admin_declaration_path %></li>
                    <li><%= link_to t("navs.versions.index"), admin_versions_path %></li>
                    <li><%= link_to t("navs.surround_city.index"), admin_surround_cities_path %></li>
                    <li><%= link_to t("navs.lijiang_mailbox.index"), admin_lijiang_mailboxes_path %></li>
                  </ul>
                </li>
              </ul>
              <ul class="nav pull-right">
                <% if user_signed_in? %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <i class="icon-user-md"></i><%= current_user.email %><b class="caret"></b>
                  </a>
                  <ul class="dropdown-menu">
                    <li class="divider"></li>
                    <li><%= link_to(t("helpers.links.logout"), destroy_user_session_path, :method => :delete) %></li>
                  </ul>
                </li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
      </div>

      <div class="container">
          <div class="row">
            <div class="span12"><%= render_breadcrumbs %></div>
            <div class="span12"><%= bootstrap_flash %></div>
            <%= render "layouts/sidebars/#{content_for?(:sidebar) ? 'two_column' : 'full_column' }" %>
          </div>

        <footer>
          <p><%= Setting.company %> &copy; Company 2013</p>
        </footer>
      </div>

    <% end %>

    <%= javascript_include_tag "admin/application" %>
    <%= yield :scripts %>
  </body>
</html>