config/routes.rb
TripMap::Application.routes.draw do

  devise_for :users,
             :path => "",
             :path_names => { :sign_in => 'login', :sign_out => 'logout' },
             :skip => [:passwords, :registrations],
             :controllers => { :sessions => 'admin/sessions' }

  resources :accounts, only: [] do
    get 'new/:device_id' => 'accounts#new', as: 'new', on: :collection
    post ':device_id' => 'accounts#create', as: '', on: :collection
    get 'success' => 'accounts#success', on: :collection
  end

  namespace :admin do
    root :to => 'home#index'

    resources :maps, :except => :show do
      resources :images, except: :show
    end

    resources :provinces, :except => :show

    resources :places, :except => :show do
      resources :images, except: :show
    end

    resources :scenics, :except => :show do
      resources :images, except: :show
    end

    resources :serialnumbers, :except => :show do
      get  'search',    on: :collection
      get  'export',    on: :collection
      post 'ex_search', on: :collection

    end

    resources :settings, :only => [] do
      match "/" => "settings#index", on: :collection, via: [:get, :post]
    end

    resources :recommends do
      resources :images, except: :show
      resources :recommend_records,
                path: 'records',:as => "records" do
        resources :recommend_detaileds, path: 'detaileds', :as => "detaileds" do
          get    'video/new'  => 'recommend_detaileds#new_video'
          post   'videos'     => 'recommend_detaileds#create_video'
          put    'video/:id'  => 'recommend_detaileds#update_video',  :as => 'video'
          delete 'video/:id'  => 'recommend_detaileds#destroy_video'
          get    'videos/:id/edit' => 'recommend_detaileds#edit_video', :as => 'video_edit'

          get    'audio/new'  => 'recommend_detaileds#new_audio'
          post   'audios'     => 'recommend_detaileds#create_audio'
          put    'audio/:id'  => 'recommend_detaileds#update_audio',  :as => 'audio'
          delete 'audio/:id'  => 'recommend_detaileds#destroy_audio'
          get    'audios/:id/edit' => 'recommend_detaileds#edit_audio', :as => 'audio_edit'

          get    'image/new'  => 'recommend_detaileds#new_image'
          post   'images'     => 'recommend_detaileds#create_image'
          put    'image/:id'  => 'recommend_detaileds#update_image',  :as => 'image'
          delete 'image/:id'  => 'recommend_detaileds#destroy_image'
          get    'images/:id/edit' => 'recommend_detaileds#edit_image', :as => 'image_edit'

          get    'imagelist/new'  => 'recommend_detaileds#new_imagelist'
          post   'imagelists'     => 'recommend_detaileds#create_imagelist'
          put    'imagelist/:id'  => 'recommend_detaileds#update_imagelist',  :as => 'imagelist'
          delete 'imagelist/:id'  => 'recommend_detaileds#destroy_imagelist'
          get    'imagelists/:id/edit'   => 'recommend_detaileds#edit_imagelist', :as => 'imagelist_edit'

          get    'imagelist/:id/images/'  => 'recommend_detaileds#images', :as => 'imageslist'
          post   'imagelist/:image_id/images'   => 'recommend_detaileds#create_images'
          put    'imagelist/:image_id/image/:id' => 'recommend_detaileds#update_images', :as => 'photos'
          delete 'imagelist/:image_id/image/:id' => 'recommend_detaileds#destroy_images'
          get    'imagelist/:image_id/image/:id/edit' => 'recommend_detaileds#edit_images', :as => 'edit_images'
          get    'imagelist/:image_id/image/new' => 'recommend_detaileds#new_images', :as => 'new_images'

          get    'text/new'  => 'recommend_detaileds#new_text'
          post   'texts'     => 'recommend_detaileds#create_text'
          put    'text/:id'  => 'recommend_detaileds#update_text',  :as => 'text'
          delete 'text/:id'  => 'recommend_detaileds#destroy_text'
          get    'text/:id/edit' => 'recommend_detaileds#edit_text', :as => 'text_edit'

          get    'detailed_info/new'  => 'recommend_detaileds#new_detailed_info'
          post   'detailed_infos'     => 'recommend_detaileds#create_detailed_info'
          put    'detailed_info/:id'  => 'recommend_detaileds#update_detailed_info',  :as => 'detailed_info'
          delete 'detailed_info/:id'  => 'recommend_detaileds#destroy_detailed_info'
          get    'detailed_info/:id/edit' => 'recommend_detaileds#edit_detailed_info', :as => 'detailed_info_edit'

        end
      end
    end

    resources :specials, :except => :show do
      resources :minorities do
        resources :minority_slides, path: 'slides', :as => "slides", :except => :show
        resources :minority_feels, path: 'feels', :as => "feels", :except => :show
      end
    end
    
    resources :fights, :except => :show do
      resources :minorities do
        resources :minority_slides, path: 'slides', :as => "slides", :except => :show
        resources :minority_feels, path: 'feels', :as => "feels", :except => :show
      end
    end

    resources :minority_feels, :only => [] do
      resources :images, except: :show
    end

    resources :info_lists do
      resources :infos
    end

    resources :shares do
      get 'publish/:status', :action => :publish, :on => :member, :as => :publish
      match 'select', :on => :collection, :via => [:get, :post]
    end

    resources :cities, :except => :show

    resources :counties, :except => :show

    resources :merchants, :except => :show do
      resources :images, except: :show
    end

    resources :logs, :only => [:index, :show] do
      match 'select', :on => :collection, :via => [:get, :post]
    end

    resources :accounts, :except => :show do
      get 'search', :on => :collection
    end

    resources :api, :only => [] do
      get 'v1', :on => :collection
    end

    match 'declaration/show' => 'declarations#show', :as => 'declaration', :via => [:get, :post, :put]

    resources :feedbacks, only: [:index, :show]

    resources :versions

    resources :weathers, only: [:index]

    resources :surround_cities

    resources :lijiang_mailboxes, only: [ :index, :destroy ]

    resources :panel_videos

    resources :broadcasts do
      resources :children_broadcasts
    end

    resources :audio_list_categories do
      resources :audio_lists do
        resources :audio_list_items
      end
    end

    resources :first_knowns, :except => :show do
      resources :images, :except => :show
      resources :first_known_lists, :except => :show do
        resources :first_known_list_items
      end
    end

    resources :downloads, :only => [] do
      get '/d', :on => :collection
    end
  end

  namespace :api do
    namespace :v1 do

      resources :maps, :only => :index do
        resources :weathers, :only => :index
        get '/show', :on => :collection
        get '/validate', :on => :collection
        get 'shares/nearby' => 'shares#nearby', :on => :collection
        get 'shares/current' => 'shares#current', :on => :collection
        post 'shares/create' => 'shares#create', :on => :collection
        post 'logs' => 'logs#create', :on => :collection
        get 'version' => 'maps#version', :on => :member
      end

      resources :accounts, only: [] do
        post '/create' => 'accounts#create', on: :collection
        post '/login' => 'accounts#login', on: :collection
        post '/update' => 'accounts#update', on: :collection
        post '/validate' => 'accounts#validate', on: :collection
        get '/show' => 'accounts#show', on: :collection
      end

      resources :declarations, only: [] do
        get '/show' => 'declarations#show', on: :collection
      end

      resources :feedbacks, only: [] do
        post '/create' => 'feedbacks#create', on: :collection
      end

      resources :versions, only: [] do
        get '/check' => 'versions#check', :on => :collection
      end

      resources :downloads, only: [] do
        get '/count' => 'downloads#count', :on => :collection
      end

      resources :merchants, only: [:index, :show]
      resources :fights, only: [:index, :show]

      resources :devices, only: [:index] do
        post '/validate' => 'devices#validate', :on => :collection
        get '/unbind_device' => 'devices#unbind_device', :on => :collection
      end

      resources :lijiang_mailboxes, only: [:create]

      resources :offline_packages, only: [] do
        get '/pkg_versions' => 'offline_packages#pkg_versions', :on => :collection
        get '/get_all_pkg_infos' => 'offline_packages#get_all_pkg_infos', :on => :collection
        get '/get_offline_pkg_url' => 'offline_packages#get_offline_pkg_url', :on => :collection
      end

    end

    namespace :v1x do
      resources :maps, :only => :index do
      end
    end
  end

  root :to => 'home#index'
end

app/models/first_known_list_item.rb
class FirstKnownListItem < ActiveRecord::Base

  # White list
  attr_accessible :first_known_list_id, :title, :description, :order,
                  :first_known_list_item_icon_attributes

  # Associations
  belongs_to :first_known_list

  with_options :as => :imageable, :class_name => 'Image', :dependent => :destroy do |assoc|
    assoc.has_one :first_known_list_item_icon,  :conditions => { :image_type => Image.first_known_list_item_icon }
  end

  # Validates
  with_options :presence => true do |column|
    column.validates :first_known_list_id
    column.validates :title, :length => { :within => 1..20, :message => I18n.t("errors.type.name") }, :uniqueness => true
    column.validates :description
  end

  validates_with OrderValidator

  # Nested attributes validates
  accepts_nested_attributes_for :first_known_list_item_icon,  reject_if: ->(attr){ attr[:file].blank? }, :allow_destroy => true

  # Scopes
  scope :created_desc, order("created_at DESC")
  scope :order_asc,    order("`order` ASC")

end

app/controllers/admin/first_known_list_items_controller.rb
class Admin::FirstKnownListItemsController < Admin::ApplicationController

  def index
    parent = FirstKnownList.find params[:first_known_list_id].to_i
    @models = parent.first_known_list_items.page(params[:page]).per(Setting.page_size).created_desc

    add_breadcrumb :index
  end

  def new
    @model = FirstKnownListItem.new

    add_breadcrumb :new
  end

  def create
    add_breadcrumb :new

    @model = FirstKnownListItem.new params[:first_known_list_item]
    if @model.save
      redirect_to admin_first_known_first_known_list_first_known_list_items_path(@model.first_known_list.first_known_id, @model.first_known_list_id),
                  notice: t('messages.commons.success')
    else
      render :new
    end
  end

  def edit
    @model = FirstKnownListItem.find params[:id]
    add_breadcrumb :edit
  end

  def update
    add_breadcrumb :edit

    @model = FirstKnownListItem.find params[:id]
    if @model.update_attributes params[:first_known_list_item]
      redirect_to admin_first_known_first_known_list_first_known_list_items_path(@model.first_known_list.first_known_id, @model.first_known_list_id),
                  notice: t('messages.commons.success')
    else
      render :edit
    end
  end

  def destroy
    @model = FirstKnownListItem.find params[:id]
    if @model.destroy
      redirect_to admin_first_known_first_known_list_first_known_list_items_path, notice: t('messages.commons.success')
    else
      redirect_to admin_first_known_first_known_list_first_known_list_items_path, alert: t('messages.commons.error')
    end
  end

end

app/views/admin/first_known_list_items/_base.html.erb
<div class="toolbar">
  <div class="btn-toolbar">

    <%= link_to_if %w(index).include?(action_name), t('links.first_known_list_items.new'), new_admin_first_known_first_known_list_first_known_list_item_path, class: 'btn btn-success' %>
    <%= link_to_if %w(index).include?(action_name), t('links.first_known_list_items.first_known_list'), admin_first_known_first_known_lists_path, class: 'btn btn-success' %>
    <%= link_to_if %w(new create edit update).include?(action_name), t('links.first_known_list_items.index'),  admin_first_known_first_known_list_first_known_list_items_path, class: 'btn btn-success' %>

  </div>
</div>

app/views/admin/first_known_list_items/_form.html.erb
<%= simple_form_for [:admin, :first_known, :first_known_list, @model], html: { class: 'form-horizontal' } do |m| %>

  <%= m.association :first_known_list, collection: FirstKnownList.all, :label_method => :title_cn, prompt: t("helpers.links.select") %>

  <%= m.input :title %>
  <%= m.input :description, :as => :text %>

  <%= m.fields_for :first_known_list_item_icon, @model.first_known_list_item_icon ||= @model.build_first_known_list_item_icon do |img|  %>
    <%= img.input :file, :as => :file %>

    <% if @model.first_known_list_item_icon && @model.first_known_list_item_icon.file.present? %>
        <div class="control-group image">
          <div class="controls">
            <%= image_tag @model.first_known_list_item_icon.file %>
          </div>
        </div>
    <% end %>
  <% end %>

  <%= m.input :order %>

  <div class="form-actions"><%= m.button :submit, :class => 'btn-primary' %></div>

<% end %>

app/views/admin/first_known_list_items/edit.html.erb
<%= render 'base' %>

<div class="box">

  <div class="box-title">
    <span class="icon"><i class="icon-edit"></i></span>
    <h5><%= t('links.audio_list_items.edit') %></h5>
  </div>

  <div class="box-content no-padding">
    <%= render 'form' %>
  </div>

</div>

app/views/admin/first_known_list_items/index.html.erb
<%- model_class = FirstKnownListItem -%>

<%= render 'base' %>

<div class="box">
  <div class="box-title">
    <span class="icon"><i class="icon-th"></i></span>
    <h5><%= t('links.audio_list_items.index') %></h5>
  </div>
  <div class="box-content">
    <table class="table table-bordered table-striped with-check">
      <thead>
        <tr>
          <th><input type="checkbox" id="title-table-checkbox" name="title-table-checkbox" /></th>
          <th><%= model_class.human_attribute_name(:first_known_list) %></th>
          <th><%= model_class.human_attribute_name(:title) %></th>
          <th><%= model_class.human_attribute_name(:first_known_list_item_icon) %></th>
          <th><%= model_class.human_attribute_name(:order) %></th>
          <th><%= model_class.human_attribute_name(:description) %></th>
          <th class="action"><%= t('links.commons.action') %></th>
        </tr>
      </thead>
      <tbody>
      <% @models.each do |m| %>
        <tr>
          <td><%= check_box_tag "children_broadcast_ids[]", m.id, false, id: "children_broadcast_#{m.id}" %></td>
          <td><%= m.first_known_list.title_cn %></td>
          <td><%= m.title %></td>
          <td><%= image_tag m.first_known_list_item_icon.file, :size => "35x35" unless m.first_known_list_item_icon.blank? %></td>
          <td><%= m.order %></td>
          <td><%= m.description.length > 20 ? (m.description[0...20] + "...") : m.description %></td>

          <td class="action">
            <%= link_to raw("<i class=\"icon-edit\"></i>"), edit_admin_first_known_first_known_list_first_known_list_item_path(params[:first_known_id], params[:first_known_list_id], m.id), title: t('links.audio_list_items.edit') %>
            <%= link_to raw("<i class=\"icon-trash\"></i>"), admin_first_known_first_known_list_first_known_list_item_path(params[:first_known_id], params[:first_known_list_id], m.id), method: :delete, data: {confirm: t('links.commons.confirm')} %>
          </td>
         </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="table-footer clearfix">
  <div class="paginates-info"><%= page_entries_info @models %></div>
  <%= paginate @models, :theme => "admin" %>
</div>

app/views/admin/first_known_list_items/new.html.erb
<%= render 'base' %>

<div class="box" %>
  <div class="box-title">
  <span class="icon"><i class="icon-pencil"></i></span>
  <h5><%= t('links.audio_list_items.new') %></h5>
  </div>

  <div class="box-content no-padding">
    <%= render "form" %>
  </div>

</div>